### ISSUE TITLE
Make the 'out of stock reminder' more visible for costumers - back in stock klaviyo

### ISSUE THREAD

**Issue by LauraToldal** [gregjotau/dawn-famme#35]
We have gotten questions in regards to why we do not have this feature. 
Maybe we can make the text bigger or instead of the 'add to cart' when the product is available that becomes the 'get a reminder' button instead. 
<img width="350" alt="Skærmbillede 2022-01-31 kl  13 27 05" src="https://user-images.githubusercontent.com/98746969/151793704-0925fa04-b268-454c-b295-8de6a35bc7f1.png">

**Comment by gregjotau** [comment]
<img width="803" alt="Screenshot 2022-03-03 at 14 03 45" src="https://user-images.githubusercontent.com/13047497/156570209-36e439bd-6a29-4c18-864d-4bfa92c61d19.png">

**Comment by gregjotau** [comment]
Just to be clear: We want the buy now / add to cart button to be changed, into a "get message when back in stock" button.

**Comment by sofiemoksness** [comment]
![Skjermbilde 2022-03-07 101005](https://user-images.githubusercontent.com/99190561/157001692-82c1c2f2-b26b-46d7-a25f-2598eaa51c31.png)

**Comment by pa-famme** [comment]
This is fixed and looks good. Instead of the "utsolgt" button, the button now says "få melding når størrelsen er tilbake", which makes it easier for the customer to see and use. 


<img width="520" alt="Skjermbilde 2022-03-08 kl  11 10 58" src="https://user-images.githubusercontent.com/92975223/157215385-c6a051bc-62d4-4941-ae11-f80b8e56fc82.png">
