### ISSUE TITLE
Buttons: Make the add to cart button unique 

### ISSUE THREAD

**Issue by rhfamme** [gregjotau/dawn-famme#43]
It is important that the "add to cart" button is unique and that the style is not used for other buttons that are in the interface. If the button is unique, it will be easier for the user to distinguish the button from other information and it will be easier for them to notice what Famme most wants them to do (add to the shopping cart and buy the item).

Similar buttons (in design) should lead to similar actions so that it is clear for the user what the different buttons lead to. The blue button that users press to add to the shopping cart is also used for, among other things, "write a Review", "to checkout" and "log in to return". This can confuse the user as the different buttons lead to completely different actions. For example, "log in to return" takes you to a whole new page, while add to cart only gives the user a pop-up window that tells you that the item has been added. 

Change the color or shape of, for example, the "add to cart" button or the others that do not lead to the same action to make the shopping cart button unique.

Read more here:
https://baymard.com/premium/guideline-collections/ke4sob/791

<img width="492" alt="Skjermbilde 2022-02-07 kl  12 54 44" src="https://user-images.githubusercontent.com/99011309/152783751-733ddbb0-84df-4930-b1cd-0e5446e23a09.png">
<img width="401" alt="Skjermbilde 2022-02-07 kl  12 54 50" src="https://user-images.githubusercontent.com/99011309/152783755-1867516b-e54f-4a93-b212-de9b3c485b41.png">
<img width="302" alt="Skjermbilde 2022-02-07 kl  12 55 14" src="https://user-images.githubusercontent.com/99011309/152783756-9a3d4b65-0a8b-44d0-b469-d4ec0908aea5.png">

**Comment by gregjotau** [comment]
Advice: Ensure the “Add to Cart” button has unique styling that isn’t reused with other buttons and clearly distinguish it as the page’s primary button. If using a sticky “Add to Cart” button surround it with sufficient white space (i.e., don’t use full-width sticky “Add to Cart” buttons).


I think that because there are very few other buttons on the PDP page, I think that reusing the styling is "fine", the examples shown in Baymard was amazon having 10 different buttons in the same viewport + avoid grey buttons etc. as it can be interpreted as sold out.
