### ISSUE TITLE
USP section - Use multi-column with small changes?

### ISSUE THREAD

**Issue by gregjotau** [gregjotau/dawn-famme#45]
https://github.com/Shopify/dawn/issues/1308

**Comment by gregjotau** [comment]
![image](https://user-images.githubusercontent.com/13047497/155614203-84af3400-d204-460a-b888-8f7bf2dbde79.png)

![image](https://user-images.githubusercontent.com/13047497/155614238-f88cc515-3a48-4a4a-bd25-3fe472c37b17.png)

Reference implementation

**Comment by gregjotau** [comment]
We do not want to mess with the dawn multi-column, as this makes it harder to merge changes from Dawn team. 

Make a new section for it, but it could be inspired by the multi-column section with changes, but not necessarily.

**Comment by pa-famme** [comment]
Is it possible to get a setting to adjust the image size more than what is possible right now? and more even size on mobile and desktop because it gets too big on the desktop version when the size is perfect on mobile. See screenshots down below.

<img width="485" alt="Skjermbilde 2022-03-08 kl  15 31 07" src="https://user-images.githubusercontent.com/92975223/157264518-be3c3b61-c520-4b7c-8fbc-94348a3de9eb.png">

<img width="1440" alt="Skjermbilde 2022-03-08 kl  15 31 02" src="https://user-images.githubusercontent.com/92975223/157264503-5989c987-ef21-423d-a7b7-9b43e3ac2c63.png">
